# Configuration for Yasb (Yet Another Status Bar)
#
watch_stylesheet: true
watch_config: true

bars:
  yasb-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 28
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:   ["komorebi_workspaces", "active_window"]
      center: []
      right:  ["cpu", "memory", "komorebi_active_layout", "clock"]

widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      max_length: 48
      max_length_ellipsis: "..."
      monitor_exclusive: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
        label: "{%H:%M:%S %Z}"
        label_alt: "{%Y-%m-%d %H:%M:%S %Z}"
        timezones: ["Asia/Tokyo", "UTC"]
        callbacks:
          on_middle: "exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"
          on_right: "next_timezone"

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "\uf200 {info[histograms][cpu_percent]} {info[percent][total]}%"
      label_alt: "\uf200 {info[percent][total]}% {info[freq][current]}MHz"
      update_interval: 500
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 10
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "\ue266 {virtual_mem_percent}%"
      label_alt: "\ue266 {virtual_mem_free} Free"
      update_interval: 5000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "{index}"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: false
      label: "{icon}"
      layout_icons:
        bsp: "\udb81\udd74"
        columns: "\udb81\udd6d"
        rows: "\udb81\udf29"
        vertical_stack: "\udb82\udfcc"
        horizontal_stack: "\udb86\udc88"
        ultrawide_vertical_stack: "\udb82\udc43"
        monocle: "\udb84\udcac"
        maximised: "\ue25d"
        floating: "\uf2d2"
        paused: "\uf04c"
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_monocle'
        on_right: 'prev_layout'
