[[plugins]]
repo = 'ellisonleao/gruvbox.nvim'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.x'
depends = [ 'plenary.nvim' ]

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'

[[plugins]]
repo = 'akinsho/bufferline.nvim'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'andersevenrud/nvim_context_vt'

[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'

[[plugins]]
repo = 'petertriho/nvim-scrollbar'

[[plugins]]
repo = 'yutkat/wb-only-current-line.nvim'

[[plugins]]
repo = 'RRethy/vim-illuminate'

[[plugins]]
repo = 'folke/which-key.nvim'

[[plugins]]
repo = 'Shougo/vinarise.vim'
