[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
	set background=dark
	let g:gruvbox_contrast_dark='hard'
	au MyAutoCmd VimEnter * nested colorscheme gruvbox
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'pepo-le/win-ime-con.nvim'
