[[plugins]]
repo = 'ellisonleao/gruvbox.nvim'
hook_add = '''
	set background=dark
	au MyAutoCmd VimEnter * nested colorscheme gruvbox
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.x'
depends = [ 'plenary.nvim' ]

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'pepo-le/win-ime-con.nvim'
